name: Build and Push AutoGPT Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - path: autogpt_platform/backend/Dockerfile
            image: backend
          - path: autogpt_platform/frontend/Dockerfile
            image: frontend
            target: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'Significant-Gravitas/AutoGPT'
          ref: 'autogpt-platform-beta-v0.6.1'
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/autogpt/${{ matrix.dockerfile.image }}
          context: git
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{version}},prefix=autogpt-platform-beta-
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.dockerfile.target }}


